Repository rsksmart/rif-scheduler-contracts, pull requests merged in 2021-06, with the labels that each got.

#33 Update ci.yml
  .github/workflows/ci.yml
  README.md
Labels: dev

#34 Publish ABI and bytecode to npm
  .gitignore
  datagen.js
  package-lock.json
  package.json
Labels: enhancement

#36 Export typechain types
  .github/workflows/ci.yml
  .gitignore
  package-lock.json
  package.json
Labels: enhancement

#37 Update README.md
  README.md
Labels: bug, documentation

#44 Security review sch 006
  .github/workflows/ci.yml
  .solcover.js
  contracts/RIFScheduler.sol
  contracts/test/Counter.sol
  contracts/test/NotPayable.sol
  contracts/test/PayableContract.sol
  package-lock.json
  package.json
  slither.config.json
  test/execution.test.js
Labels: bug

#49 SCH-007 Payee is paying for the scheduled transaction
  contracts/RIFScheduler.sol
  migrations/2_deploy_contracts.js
  test/common.js
  test/execution.test.js
  test/multicall.test.js
  test/plans.test.js
  test/purchase.test.js
  test/scheduling.test.js
Labels: bug
